### ISSUE TITLE
Information Measure Change does not influence the model

### ISSUE THREAD

**Issue by spideralessio** [Mereep/HDTree#1]
```
class AccuracyMeasure(AbstractInformationMeasure):
    def supports_regression(self):
        return False

    def supports_classification(self):
        return True

    def calculate_for_children(self, parent_node):
        child_nodes = parent_node.get_children()
        if child_nodes is None:
            child_nodes = []

        node = None
        # calculate accuracy for each node

        n_total_samples = sum(len(node.get_labels()) for node in child_nodes)
        pureness_childs = 0.
        for node in child_nodes:
            child_cats = node.get_labels()
            accuracy = self.calculate_for_single_node(node=node)
            pureness_childs += accuracy*1/len(child_nodes)# * len(child_cats)/n_total_samples
        return np.random.uniform()

    def calculate_for_labels(self, labels, normalize=True):
        node_cats = labels
        most_common_class = Counter(node_cats).most_common()[0][0]
        accuracy = sum(node_cats == most_common_class) / len(node_cats)
        print("ciao")
        return np.random.uniform()

hdtree_linear_acc = HDTreeClassifier(max_levels=15, allowed_splits=[SmallerThanSplit.build()],
                                 information_measure=AccuracyMeasure())

hdtree_linear_entropy = HDTreeClassifier(max_levels=15, allowed_splits=[SmallerThanSplit.build()],
                                 information_measure=EntropyMeasure())
```

Hi I am trying to define a new measure but I have noticed that using random scores we obtain the same results of EntropyMeasure

EntropyMeasure
acc 0.8354972039873572
prec 0.4819277108433735
recall 0.05938242280285035
f1 0.10573618821041501

AccuracyMeasure
acc 0.8354972039873572
prec 0.4819277108433735
recall 0.05938242280285035
f1 0.10573618821041501

**Comment by Mereep** [comment]
Hi and thanks for the report,


I was trying your split as is on the titanic dataset; yielding different results for your Random Split implementation and the Entropy Implementation. I uploaded it as github gist here: https://gist.github.com/Mereep/507884f3725bced23e11124abe8b372f (or; if you have a google account into Colabs: https://colab.research.google.com/drive/1Zzi_d6HkuO78zpNLgY2u6A9ov1geSiAr?usp=sharing)

What kind of data you are using? I see that you use only the `SmallerThanSplit` as allowed split. 
Maybe the following is happening: If you use a dataset with only two numeric attributes, than there will be only one choice for the split (namely `attribute1 < attribute2` or vise versa), no matter what the Measure is saying.

Maybe you can look into this?

**Comment by Mereep** [comment]
Hi, since I did not get any review and my tests didn't indicate the issue to be, I will close this for now. If you encounetr the problem still or have any further info, feel free to reopen a ticket.
