### ISSUE TITLE
Puzzle of why the sum of childrens' sample size is not equal to the parents' sample size 

### ISSUE THREAD

**Issue by RenJump** [Mereep/HDTree#2]
I am reading the introduction article, while I found that under some split rules, the sum of sample size of children != the sample size of their parent.

For example, 
![image](https://user-images.githubusercontent.com/58929182/227115255-9a6f82b7-e3af-4f24-b88f-193dc5145f18.png)
the sum sample size of the first one and second one node in level 2 equals to 117 + 359 = 476, while their parents only have 390 sample.

**Comment by Mereep** [comment]
Hi,

The tree has support for missing values. If it splits on Attributes containing missing values, it will pass the data onto both parts, effectively increasing the childs total sample count.
